### ISSUE TITLE
Where can I find the documentation?

### ISSUE THREAD

**Issue by nbro** [alipsgh/tornado#1]

**Comment by alipsgh** [comment]
Hello,

You may have a look at my [thesis](https://ruor.uottawa.ca/bitstream/10393/38190/1/Pesaranghader_Ali_2018_thesis.pdf) where you can find more information about the algorithms. Source codes are well-commented, and please drop me an email if you have any other questions.

Cheers,

**Comment by nbro** [comment]
@alipsgh I've looked at two random `.py` files and they are not well documented. I think that any serious piece of software needs to be well documented (even if there is your thesis, etc), so you should keep this issue opened.

**Comment by alipsgh** [comment]
True, and thanks. Please drop here any question you have regarding any class; I'll be glad to help you out.
