### ISSUE TITLE
Make available drift detectors

### ISSUE THREAD

**Issue by maffei2443** [alipsgh/tornado#2]
Hello.
I sort of accidentally find this repo while performing the literature review for my conclusion of work project and became very interested on the concept drift detectors implemented.
However, I could not find a practical way of accessing the methods of **concept_drift** folder.

Is there any interest of yours in making it available stand-alone or, maybe, integrating it on River?
Anyway,  I  will try to use this detectors on my own and can share my adaptions on the code so that is may be used by itself.

**Comment by alipsgh** [comment]
Hey,
You can find the evaluator for drift detection here: https://github.com/alipsgh/tornado/blob/master/evaluators/detector_evaluator.py
Evaluators are in the `./evaluators/` folder.
