### ISSUE TITLE
do you have Fast Hoeffding Drift Detection Method for Evolving Data Streams

### ISSUE THREAD

**Issue by Sandy4321** [alipsgh/tornado#4]
do you have implemented 
Pesaranghader, Ali, et al. "Fast Hoeffding Drift Detection Method for Evolving Data Streams", European Conference on Machine Learning, 2016.
Pre-print available at: http://iwera.ir/~ali/papers/ecml2016.pdf, DOI: https://doi.org/10.1007/978-3-319-46227-1_7
Pesaranghader, Ali, et al. "McDiarmid Drift Detection Methods for Evolving Data Streams", International Joint Conference on Neural Networks, 2018.
Pre-print available at: https://arxiv.org/abs/1710.02030, DOI: https://doi.org/10.1109/IJCNN.2018.8489260

as in java code repo?

**Comment by alipsgh** [comment]
Hello,

Thank you for your message. I hope the following links help.

- Python Implementation: https://github.com/alipsgh/tornado/blob/master/drift_detection/fhddm.py
- Java Implementation: https://github.com/alipsgh/codes-for-moa/blob/master/drift_detection/FHDDM.java

Cheers,

**Comment by Sandy4321** [comment]
great thanks
to make it clear how to use it
may you share stand alone python code how to use it
1
input data set
2
how to call https://github.com/alipsgh/tornado/blob/master/drift_detection/fhddm.py
3
what result should be ?

**Comment by aditya0by0** [comment]
In other words, it would be very helpful if you could share a test case for methods like MDDM and FHDDM, along with sample generated data. For example, something along the lines of:

```python
import numpy as np

np.random.seed(12345)
data_stream_1 = np.concatenate([
    [np.random.binomial(1, 0.2) for _ in range(1000)],
    [np.random.binomial(1, 0.8) for _ in range(1000)],
]).astype(int)

def test_mddm_a():
    mddm_a = MDDM_A()
    expected_indices = [1018]
    detected_indices = perform_test(mddm_a, data_stream_1)
    assert detected_indices == expected_indices
```

Having a concrete example like this would greatly clarify usage and testing for these drift detection methods. Thank you!
